// suppliers.service.ts
import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { Supplier } from './supplier.model';

@Injectable({
  providedIn: 'root',
})
export class SuppliersService {
  // sample-suppliers.ts
  private suppliers: Supplier[] = [
    {
      id: 1,
      name: 'Al Nour Supplies',
      contactNumber: '0912345678',
      email: 'contact@alnour.sd',
      address: 'Al Souq Al Arabi',
      city: 'Khartoum',
      state: 'Khartoum',
      country: 'Sudan',
      postalCode: '11111',
      website: 'www.alnour.sd',
      contactPerson: 'Mohamed El Tayeb',
      contactPersonNumber: '0923456789',
      contactPersonEmail: 'mohamed@alnour.sd',
      createdAt: '2023-01-12',
      updatedAt: '2024-03-20',
      status: 'Active',
    },
    {
      id: 2,
      name: 'Bahri Industrial Co.',
      contactNumber: '0921123344',
      email: 'info@bahriind.sd',
      address: 'Bahri Industrial Area',
      city: 'Bahri',
      state: 'Khartoum',
      country: 'Sudan',
      postalCode: '12221',
      website: 'www.bahriind.sd',
      contactPerson: 'Fatima Osman',
      contactPersonNumber: '0912233445',
      contactPersonEmail: 'fatima@bahriind.sd',
      createdAt: '2022-11-05',
      updatedAt: '2024-02-10',
      status: 'Active',
    },
    {
      id: 3,
      name: 'Blue Nile Traders',
      contactNumber: '0919988776',
      email: 'bntraders@blue.sd',
      address: 'Omdurman Market',
      city: 'Omdurman',
      state: 'Khartoum',
      country: 'Sudan',
      postalCode: '11333',
      website: 'www.bluenile.sd',
      contactPerson: 'Ahmed Musa',
      contactPersonNumber: '0965443321',
      contactPersonEmail: 'ahmed@bluenile.sd',
      createdAt: '2021-07-19',
      updatedAt: '2024-01-18',
      status: 'Inactive',
    },
    {
      id: 4,
      name: 'Sudan AgriTech',
      contactNumber: '0901234567',
      email: 'support@agritech.sd',
      address: 'Al Qadarif Main Street',
      city: 'Gedaref',
      state: 'Gedaref',
      country: 'Sudan',
      postalCode: '44121',
      website: 'www.agritech.sd',
      contactPerson: 'Huda Abdelrahim',
      contactPersonNumber: '0993344556',
      contactPersonEmail: 'huda@agritech.sd',
      createdAt: '2023-06-15',
      updatedAt: '2024-04-01',
      status: 'Active',
    },
    {
      id: 5,
      name: 'Nile Valley Exports',
      contactNumber: '0917766554',
      email: 'exports@nilevalley.sd',
      address: 'Port Sudan Dock 3',
      city: 'Port Sudan',
      state: 'Red Sea',
      country: 'Sudan',
      postalCode: '21111',
      website: 'www.nilevalley.sd',
      contactPerson: 'Osman Idris',
      contactPersonNumber: '0911223344',
      contactPersonEmail: 'osman@nilevalley.sd',
      createdAt: '2022-04-10',
      updatedAt: '2023-12-23',
      status: 'Active',
    },

    // ... 25 more suppliers below
    {
      id: 6,
      name: 'Sahara Traders',
      contactNumber: '0999888776',
      email: 'info@sahara.sd',
      address: 'El Fasher Main Market',
      city: 'El Fasher',
      state: 'North Darfur',
      country: 'Sudan',
      postalCode: '22122',
      website: 'www.saharatraders.sd',
      contactPerson: 'Yasir Elamin',
      contactPersonNumber: '0922001122',
      contactPersonEmail: 'yasir@sahara.sd',
      createdAt: '2021-10-02',
      updatedAt: '2024-03-30',
      status: 'Active',
    },
    {
      id: 7,
      name: 'Gezira Farm Supplies',
      contactNumber: '0912233445',
      email: 'sales@gezira.sd',
      address: 'Al Manaqil Road',
      city: 'Wad Madani',
      state: 'Gezira',
      country: 'Sudan',
      postalCode: '31122',
      website: 'www.gezirafarms.sd',
      contactPerson: 'Ahlam Hassan',
      contactPersonNumber: '0933445566',
      contactPersonEmail: 'ahlam@gezira.sd',
      createdAt: '2020-03-11',
      updatedAt: '2024-02-08',
      status: 'Inactive',
    },
    {
      id: 8,
      name: 'Unity Construction',
      contactNumber: '0923445566',
      email: 'contact@unityco.sd',
      address: 'Al Shajara Area',
      city: 'Khartoum',
      state: 'Khartoum',
      country: 'Sudan',
      postalCode: '11444',
      website: 'www.unityco.sd',
      contactPerson: 'Tarig Mohammed',
      contactPersonNumber: '0966778899',
      contactPersonEmail: 'tarig@unityco.sd',
      createdAt: '2022-12-22',
      updatedAt: '2024-01-15',
      status: 'Active',
    },
    {
      id: 9,
      name: 'Unity Construction',
      contactNumber: '0923445566',
      email: 'contact@unityco.sd',
      address: 'Al Shajara Area',
      city: 'Khartoum',
      state: 'Khartoum',
      country: 'Sudan',
      postalCode: '11444',
      website: 'www.unityco.sd',
      contactPerson: 'Tarig Mohammed',
      contactPersonNumber: '0966778899',
      contactPersonEmail: 'tarig@unityco.sd',
      createdAt: '2022-12-22',
      updatedAt: '2024-01-15',
      status: 'Active',
    },
    {
      id: 10,
      name: 'Unity Construction',
      contactNumber: '0923445566',
      email: 'contact@unityco.sd',
      address: 'Al Shajara Area',
      city: 'Khartoum',
      state: 'Khartoum',
      country: 'Sudan',
      postalCode: '11444',
      website: 'www.unityco.sd',
      contactPerson: 'Tarig Mohammed',
      contactPersonNumber: '0966778899',
      contactPersonEmail: 'tarig@unityco.sd',
      createdAt: '2022-12-22',
      updatedAt: '2024-01-15',
      status: 'Active',
    },
    {
      id: 11,
      name: 'Unity Construction',
      contactNumber: '0923445566',
      email: 'contact@unityco.sd',
      address: 'Al Shajara Area',
      city: 'Khartoum',
      state: 'Khartoum',
      country: 'Sudan',
      postalCode: '11444',
      website: 'www.unityco.sd',
      contactPerson: 'Tarig Mohammed',
      contactPersonNumber: '0966778899',
      contactPersonEmail: 'tarig@unityco.sd',
      createdAt: '2022-12-22',
      updatedAt: '2024-01-15',
      status: 'Active',
    },
  ];

  getSuppliersList(): Observable<Supplier[]> {
    return of(this.suppliers);
  }
}
